openapi: 3.0.0
info:
  title: API de Contas a Pagar
  version: 1.0.0
  description: Documentação da API para contas, categorias e formas de pagamento
servers:
  - url: http://localhost:5000

paths:
  /api/bills:
    get:
      summary: Lista todas as contas do usuário autenticado
      tags: [Bills]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Lista retornada com sucesso
    post:
      summary: Cria uma nova conta
      tags: [Bills]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Bill"
      responses:
        201:
          description: Conta criada com sucesso

  /api/bills/{id}:
    get:
      summary: Retorna uma conta específica do usuário
      tags: [Bills]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conta encontrada
        404:
          description: Conta não encontrada
    put:
      summary: Atualiza uma conta do usuário
      tags: [Bills]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Bill"
      responses:
        200:
          description: Conta atualizada
    delete:
      summary: Deleta uma conta do usuário
      tags: [Bills]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conta deletada

  /api/category:
    get:
      summary: Lista todas as categorias do usuário
      tags: [Category]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Lista de categorias
    post:
      summary: Cria uma nova categoria
      tags: [Category]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        201:
          description: Categoria criada

  /api/category/{id}:
    get:
      summary: Retorna uma categoria específica
      tags: [Category]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Categoria encontrada
        404:
          description: Categoria não encontrada
    put:
      summary: Atualiza uma categoria
      tags: [Category]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: Categoria atualizada
    delete:
      summary: Deleta uma categoria
      tags: [Category]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Categoria deletada

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Bill:
      type: object
      required:
        - name
        - value
        - category
        - userId
      properties:
        name:
          type: string
        value:
          type: number
        installments:
          type: number
        installmentsPayed:
          type: number
        isRecurring:
          type: boolean
        nextPaymentDate:
          type: string
          format: date
        description:
          type: string
        category:
          type: string
        userId:
          type: string

    Category:
      type: object
      required:
        - name
        - userId
      properties:
        name:
          type: string
        userId:
          type: string