name: Deploy Backend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker --quiet

      - name: Build & Push Docker image
        working-directory: ./server
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/financa-facil-backend"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/financa-facil-backend"
          gcloud run deploy financa-facil-backend \
            --image $IMAGE \
            --region southamerica-east1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars FIREBASE_SERVICE_ACCOUNT_BASE64=${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }},MONGO_URI=${{ secrets.MONGO_URI }}